# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37f74f5db4720a67a7ef30d0fd02c8e3141195394c927b80224573a765cfc1b54e4d7b24453fb37514478c35b534e7e02d19ed42444951ef75e1beafcf56ad58

test:
  secret_key_base: bd5f1396af4a959823d2ca03c4e34b43a2018ad590b59570ed8ad1c819afc7c7e3f339458da8010febee30a5b887bea916a01319ae5a789e3c0fdcc577c62b34

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
