Company.create!(id: 1, title: '피씨방')
Company.create!(id: 2, title: '매점')
Company.create!(id: 3, title: '임시 매점')

Branch.create!(id: 1, company_id: 1, title: '피씨방', sample: true)
Branch.create!(id: 2, company_id: 2, title: '매점')
Branch.create!(id: 3, company_id: 3, title: '임시 매점')

Admin.create!(:id=>1,:branch_id=>1,:email => 'admin@sleepinglion.pe.kr',:name=>'잠자는-사자',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app","assets", "images", "dog.png")))
Admin.create!(:id=>2,:branch_id=>1,:parent_id=>1,:email=>'sub_admin@sleepinglion.pe.kr',:name=>'서브관리자',:password => 'a12345', :password_confirmation => 'a12345',:photo=>File.open(Rails.root.join("app","assets", "images", "dog.png")))
Admin.create!(:id=>3,:branch_id=>1,:parent_id=>1,:email=>'operator@sleepinglion.pe.kr',:name=>'운영자',:password => 'a12345', :password_confirmation => 'a12345',:photo=>File.open(Rails.root.join("app","assets", "images", "dog.png")))
Admin.create!(:id=>4,:branch_id=>1,:parent_id=>1,:email=>'clinomics@sleepinglion.pe.kr',:name=>'출력원',:password => 'a12345', :password_confirmation => 'a12345',:photo=>File.open(Rails.root.join("app","assets", "images", "dog.png")))
Admin.create!(:id=>5,:branch_id=>1,:parent_id=>1,:email=>'reader@sleepinglion.pe.kr',:name=>'읽기전용',:password => 'a12345', :password_confirmation => 'a12345',:photo=>File.open(Rails.root.join("app","assets", "images", "dog.png")))

Role.create!(:id=>1,:title=>'administrator')
Role.create!(:id=>2,:title=>'operator')
Role.create!(:id=>3,:title=>'store_manager')
Role.create!(:id=>4,:title=>'cs_manager')
Role.create!(:id=>5,:title=>'reader')

RolesAdmin.create!(:role_id=>1,:admin_id=>1)
RolesAdmin.create!(:role_id=>1,:admin_id=>2)
RolesAdmin.create!(:role_id=>1,:admin_id=>3)
RolesAdmin.create!(:role_id=>2,:admin_id=>4)
RolesAdmin.create!(:role_id=>3,:admin_id=>5)

Payment.create!(:id=>1,:title=>'현금결제')
Payment.create!(:id=>2,:title=>'카드결제')
Payment.create!(:id=>3,:title=>'포인트결제')
Payment.create!(:id=>4,:title=>'추후청구')
Payment.create!(:id=>5,:title=>'핸드폰결제')
Payment.create!(:id=>6,:title=>'계좌이체')
Payment.create!(:id=>7,:title=>'가상계좌')
Payment.create!(:id=>8,:title=>'무통장입금')

BranchesPayment.create!(branch_id: 1, payment_id: 1)
BranchesPayment.create!(branch_id: 1, payment_id: 2)
BranchesPayment.create!(branch_id: 1, payment_id: 3)
BranchesPayment.create!(branch_id: 1, payment_id: 4)

AccountCategory.create!(id: 1, title: '구입', enable: true)
AccountCategory.create!(id: 2, title: '수정', enable: true)
AccountCategory.create!(id: 3, title: '환불', enable: true)
AccountCategory.create!(id: 4, title: '포인트충전', enable: true)
AccountCategory.create!(id: 5, title: '포인트환불', enable: true)

ProductCategory.create!(id: 1, branch_id: 1, title: '커피', enable: true)
ProductCategory.create!(id: 2, branch_id: 1, title: '음료', enable: true)
ProductCategory.create!(id: 3, branch_id: 1, title: '간식', enable: true)


User.create!(:id=>1,:branch_id=>1,:name=>'user1',:email => 'toughjjh@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:gender=>1,:height=>180,:weight=>80,:enable=>true)
User.create!(:id=>2,:branch_id=>1,:name=>'user2',:email => 'toughjjh1@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:gender=>1,:enable=>true)
User.create!(:id=>3,:branch_id=>1,:name=>'user3',:email => 'toughjjh2@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:height=>160,:weight=>55,:enable=>true)
User.create!(:id=>4,:branch_id=>1,:name=>'user4',:email => 'toughjjh3@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:gender=>1,:enable=>true)
User.create!(:id=>5,:branch_id=>1,:name=>'user5',:email => 'toughjjh4@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:enable=>true)
User.create!(:id=>6,:branch_id=>1,:name=>'user6',:email => 'toughjjh5@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:height=>170,:weight=>65,:enable=>true)

Product.create!(:branch_id=>1,product_category_id: 1,:title=>'product1',:description=>'Good Propduct1',:price=>150001,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 1,:title=>'product2',:description=>'Good Propduct2',:price=>150002,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 1,:title=>'product3',:description=>'Good Propduct3',:price=>150003,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 1,:title=>'product4',:description=>'Good Propduct4',:price=>150004,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 2,:title=>'product5',:description=>'Good Propduct5',:price=>150005,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 2,:title=>'product6',:description=>'Good Propduct6',:price=>150006,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 2,:title=>'product7',:description=>'Good Propduct7',:price=>150007,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 2,:title=>'product8',:description=>'Good Propduct8',:price=>150008,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 3,:title=>'product9',:description=>'Good Propduct9',:price=>150009,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 3,:title=>'product10',:description=>'Good Propduct10',:price=>150010,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 3,:title=>'product11',:description=>'Good Propduct11',:price=>150011,:enable=>true)
Product.create!(:branch_id=>1,product_category_id: 3,:title=>'product12',:description=>'Good Propduct12',:price=>150012,:enable=>true)

#Order.create!(:id=>1,:user_id=>1,:last_transaction_date=>Date.today,:total_price=>20000,:total_discount=>2000,:total_payment=>18000 ,:enable=>true)
#Shipping.create!(:id=>1,:order_id=>1,:name=>'정종호',:zip_code=>'123535',:address_default=>'123521',:address_detail=>'1235235',:phone=>'2351235',:email=>'123512@tgaweg.net',:enable=>true)
