Admin.create(:id=>1,:login_id=>'toughjjh',:email => 'toughjjh@gmail.com',:nickname=>'잠자는-사자',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>2,:login_id=>'admin',:email => 'jpark@myseven.co.kr',:nickname=>'Jon Doe',:password => '111111', :password_confirmation => '111111',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>3,:parent_id=>2,:login_id=>'admin2',:email => 'jpark1@myseven.co.kr',:nickname=>'Jon Doe1',:password => '111111', :password_confirmation => '111111',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>4,:parent_id=>2,:login_id=>'operator',:email => 'jpark2@myseven.co.kr',:nickname=>'Operator',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>5,:parent_id=>2,:login_id=>'sub_operator',:email => 'jpark5@myseven.co.kr',:nickname=>'SubOperator',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>6,:parent_id=>2,:login_id=>'reader',:email => 'jpark4@myseven.co.kr',:nickname=>'Reader',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>7,:parent_id=>2,:login_id=>'sponsor',:email => 'jpark6@myseven.co.kr',:nickname=>'Sponsor',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>8,:parent_id=>2,:login_id=>'ad_manager',:email => 'jpark4@mysrheven.co.kr',:nickname=>'ad_manager',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>9,:parent_id=>2,:login_id=>'store_manager',:email => 'jpark6@myserheven.co.kr',:nickname=>'store_manager',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))
Admin.create(:id=>10,:parent_id=>2,:login_id=>'cs_manager',:email => 'jpark6@myserhevwegen.co.kr',:nickname=>'cs',:password => '123456', :password_confirmation => '123456',:photo=>File.open(Rails.root.join("app", "assets", "images", "dog.png")))

Role.create(:id=>1,:title=>'administrator')
Role.create(:id=>2,:title=>'operator')
Role.create(:id=>3,:title=>'store_manager')
Role.create(:id=>4,:title=>'cs_manager')
Role.create(:id=>5,:title=>'reader')

RolesAdmin.create(:role_id=>1,:admin_id=>1)
RolesAdmin.create(:role_id=>1,:admin_id=>2)
RolesAdmin.create(:role_id=>1,:admin_id=>3)
RolesAdmin.create(:role_id=>2,:admin_id=>4)
RolesAdmin.create(:role_id=>3,:admin_id=>5)
RolesAdmin.create(:role_id=>4,:admin_id=>6)
RolesAdmin.create(:role_id=>5,:admin_id=>7)

User.create(:id=>1,:name=>'user1',:email => 'toughjjh@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:sex=>1,:height=>180,:weight=>80,:enable=>true)
User.create(:id=>2,:name=>'user2',:email => 'toughjjh1@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:sex=>1,:enable=>true)
User.create(:id=>3,:name=>'user3',:email => 'toughjjh2@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:height=>160,:weight=>55,:enable=>true)
User.create(:id=>4,:name=>'user4',:email => 'toughjjh3@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:sex=>1,:enable=>true)
User.create(:id=>5,:name=>'user5',:email => 'toughjjh4@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:enable=>true)
User.create(:id=>6,:name=>'user6',:email => 'toughjjh5@gmail.com',:password => '123456', :password_confirmation => '123456', :birthday=>'2016-07-03', :phone=>'010-4141-3726',:height=>170,:weight=>65,:enable=>true)

Payment.create(:id=>1,:title=>'카드결제',:enable=>true)
Payment.create(:id=>2,:title=>'핸드폰결제',:enable=>false)
Payment.create(:id=>3,:title=>'계좌이체',:enable=>false)
Payment.create(:id=>4,:title=>'가상계좌',:enable=>false)
Payment.create(:id=>5,:title=>'무통장입금',:enable=>false)

Product.create(:title=>'Check Service',:description=>'Good Service',:price=>150000,:shipping_price=>3000,:enable=>true)

Shipping.create(:id=>1,:name=>'정종호',:zip_code=>'123535',:address_default=>'123521',:address_detail=>'1235235',:phone=>'2351235',:email=>'123512@tgaweg.net',:enable=>true)
Order.create(:id=>1,:user_id=>1,:shipping_id=>1,:payment_id=>1,:total_price=>20000,:enable=>true)

ReportCategory.create(:id=>1,:title=>'중점관리',:sub_title=>'중점관리가 필요함',:color=>'red',:enable=>true)
ReportCategory.create(:id=>2,:title=>'관리',:sub_title=>'관리가 필요함',:color=>'yellow',:enable=>true)
ReportCategory.create(:id=>3,:title=>'양호',:sub_title=>'양호',:color=>'blue',:enable=>true)

RelatedAction.create(:id=>1,:title=>'색소침착',:sub_title=>'pigmentation',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나, 이는 개개인에 따라 정도와 가능성에 차이가 있습니다. 이러한 색소침착의 작용은 피부에 분포하는 멜라닌이라고 불리는 색소에 의해 조절됩니다. 멜라닌이란 흑갈색의 색소로, 자외선을 흡수하여 피부로 침투되는 자외선을 차단하는 역할을 합니다. 이러한 멜라닌의 양은 개개인의 피부색을 결정짓는 요소이기도 합니다. 색소침착관련 유전자에 주의 유전형이 있다는 것은 <b>멜라닌의 합성작용에 이상이 생겨 햇빛에 대한 비부보호능이 감소</b>하거나, <b>색소침착의 가능성이 높아질 수 있다는 것</b>을 의미합니다.')
RelatedAction.create(:id=>2,:title=>'혈당',:sub_title=>'blood sugar',:enable=>true,:tip=>'혈당은 혈액속에 포함된 포도당을 의미하며, 건강한 일반인의 경우 혈당은 혈액 속에서 적절한 농도를 유지하고 있습니다. 포도당은 뇌세포의 에너지원으로 매우 주요한 성분이지만 적절한 농도를 유지하지 못하고 수치가 상승할 경우 당뇨병등이 발병될 수 있어 적절한 수치유지가 중요합니다. 우리몸의 췌장 베타세포는 혈당의 수치를 감지하고, 인슐린을 적절히 분비하여 혈당수치를 유지하는 기능을 합니다. 혈당 관련 유전자에 주의유전형이 있다는 것은<b>췌장의 베타세포기능 및 당분분해효소에 이상이 생겨 인슐린의 분비능력 저하 및 포도당의 대사에 문제가 생길 수 있다는 것을 의미</b>합니다. 고혈당 상태가 계속 유지될 경우 <b>당뇨병 및 각종 합병증 발생</b>의 가능성이 높아지게 됩니다.')
RelatedAction.create(:id=>3,:title=>'체질량지수',:sub_title=>'BMI',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>4,:title=>'혈압',:sub_title=>'blood pressure',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>5,:title=>'탈모',:sub_title=>'hair loss',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>6,:title=>'모발굵기',:sub_title=>'hair thickness',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>7,:title=>'피부노화',:sub_title=>'skin aging',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>8,:title=>'피부탄력',:sub_title=>'elasticity of skin',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>9,:title=>'중성지방농도',:sub_title=>'triglycerides',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>10,:title=>'콜레스테롤',:sub_title=>'cholesterol',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>11,:title=>'비타민 C 농도',:sub_title=>'vitamin C',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')
RelatedAction.create(:id=>12,:title=>'카페인대사',:sub_title=>'caffeine',:enable=>true,:tip=>'햇빛이 강한날에 야외활동을 오래한다면 누구나 피부에 색소침착이 생길 수 있으나')

Gene.create(:id=>1,:title=>'색소 형성 단백질 생산',:sub_title=>'OCA2',:genotype=>'AA',:factor=>'G',:description=>'피부의 색소 침착 정도가 평균보다 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>2,:title=>'피부 색소침착',:sub_title=>'MC1R',:genotype=>'GG',:factor=>'A',:description=>'유멜라닌의 생성능이 감소되고 페오멜라닌 생성이 높아져 햇빛에 대한 보호능력이 떨어질 수 있습니다.',:enable=>true)
Gene.create(:id=>3,:title=>'인슐린 분비능',:sub_title=>'CDKN2A/2B',:genotype=>'CC',:factor=>'T',:description=>'인슐린 분비능이 상대적으로 떨어질 수 있습니다.',:enable=>true)
Gene.create(:id=>4,:title=>'공복시 형당치의 상승',:sub_title=>'G6PC2',:genotype=>'GG',:factor=>'A',:description=>'인슐린의 분비가 상대적으로 감소되어 혈당이 상승할 수 있습니다.',:enable=>true)
Gene.create(:id=>5,:title=>'체내 인슐린 분비',:sub_title=>'SLC30A7',:genotype=>'TT',:factor=>'C',:description=>'체내 인슐린분비가 상대적으로 떨어져 혈당수치가 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>6,:title=>'혈당 수치',:sub_title=>'DGKB-TMEM195',:genotype=>'GG',:factor=>'T',:description=>'인슐린의 반응성이 상대적으로 떨어져 혈당수치가 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>7,:title=>'공복시혈당조절1',:sub_title=>'GCK',:genotype=>'GG',:factor=>'A',:description=>'피부의 색소 침착 정도가 평균보다 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>8,:title=>'공복시혈당조절2',:sub_title=>'GLIS3',:genotype=>'GG',:factor=>'A',:description=>'유멜라닌의 생성능이 감소되고 페오멜라닌 생성이 높아져 햇빛에 대한 보호능력이 떨어질 수 있습니다.',:enable=>true)
Gene.create(:id=>9,:title=>'공복시혈당조절3',:sub_title=>'MTNR1B',:genotype=>'CC',:factor=>'G',:description=>'인슐린 분비능이 상대적으로 떨어질 수 있습니다.',:enable=>true)
Gene.create(:id=>10,:title=>'지방축적',:sub_title=>'FTO',:genotype=>'TT',:factor=>'A',:description=>'인슐린의 분비가 상대적으로 감소되어 혈당이 상승할 수 있습니다.',:enable=>true)
Gene.create(:id=>11,:title=>'에너지소비',:sub_title=>'MC4R',:genotype=>'TT',:factor=>'C',:description=>'체내 인슐린분비가 상대적으로 떨어져 혈당수치가 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>12,:title=>'과식유발',:sub_title=>'BDNF',:genotype=>'AA',:factor=>'G',:description=>'인슐린의 반응성이 상대적으로 떨어져 혈당수치가 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>13,:title=>'수축기혈압 1',:sub_title=>'NPR3',:genotype=>'CC',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>14,:title=>'수축기혈압 2',:sub_title=>'ATP2B1',:genotype=>'AA',:factor=>'G',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>15,:title=>'수축기혈압 3',:sub_title=>'NT5C2',:genotype=>'CC',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다..',:enable=>true)
Gene.create(:id=>16,:title=>'확장기혈압 1',:sub_title=>'CSK',:genotype=>'GG',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>17,:title=>'고혈압위험도',:sub_title=>'HECTD4',:genotype=>'AA',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>18,:title=>'수축,확장기혈압',:sub_title=>'GUCY1A3-GUCY1B3',:genotype=>'CC',:factor=>'C',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다..',:enable=>true)
Gene.create(:id=>19,:title=>'수축기혈압 4',:sub_title=>'CYP17A1',:genotype=>'CC',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)
Gene.create(:id=>20,:title=>'확장기 혈압 2',:sub_title=>'FGF5',:genotype=>'AA',:factor=>'T',:description=>'혈압의 조절능력이 상대적으로 떨어져 수축기혈압이 높아질 수 있습니다.',:enable=>true)


Relation.create(:id=>1,:enable=>true,:title=>'멜라닌 생성에 주요 역할')
Relation.create(:id=>2,:enable=>true,:title=>'피부의 색소침착에 관여')
Relation.create(:id=>3,:enable=>true,:title=>'모발생상 관여')
Relation.create(:id=>4,:enable=>true,:title=>'피부색 관여 ')
Relation.create(:id=>5,:enable=>true,:title=>'점의 수 관여')
Relation.create(:id=>6,:enable=>true,:title=>'주근깨 관여')
Relation.create(:id=>7,:enable=>true,:title=>'인종간 눈의 색상에 관여')
Relation.create(:id=>8,:enable=>true,:title=>'멜라닌 전자기전 조절에 관여')
Relation.create(:id=>9,:enable=>true,:title=>'멜라닌붑비 관여')
Relation.create(:id=>10,:enable=>true,:title=>'피부색 관여')
Relation.create(:id=>11,:enable=>true,:title=>'모발색상 관여')
Relation.create(:id=>12,:enable=>true,:title=>'인슐린 분비감소 관여')
Relation.create(:id=>13,:enable=>true,:title=>'포도당 농도 증가 관여')
Relation.create(:id=>14,:enable=>true,:title=>'당뇨병 연관')
Relation.create(:id=>15,:enable=>true,:title=>'췌장 베타세포')
Relation.create(:id=>16,:enable=>true,:title=>'인슐린생산에 관여')
Relation.create(:id=>17,:enable=>true,:title=>'인슐린 반응성 감소 관여')

GenesRelatedAction.create(:related_action_id=>1,:gene_id=>1)
GenesRelatedAction.create(:related_action_id=>1,:gene_id=>2)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>3)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>4)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>5)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>6)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>7)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>8)
GenesRelatedAction.create(:related_action_id=>2,:gene_id=>9)
GenesRelatedAction.create(:related_action_id=>3,:gene_id=>10)
GenesRelatedAction.create(:related_action_id=>3,:gene_id=>11)
GenesRelatedAction.create(:related_action_id=>3,:gene_id=>12)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>13)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>14)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>15)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>16)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>17)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>18)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>19)
GenesRelatedAction.create(:related_action_id=>4,:gene_id=>20)

GenesRelation.create(:gene_id=>1,:relation_id=>1)
GenesRelation.create(:gene_id=>1,:relation_id=>2)
GenesRelation.create(:gene_id=>1,:relation_id=>3)
GenesRelation.create(:gene_id=>1,:relation_id=>4)
GenesRelation.create(:gene_id=>1,:relation_id=>5)
GenesRelation.create(:gene_id=>1,:relation_id=>6)
GenesRelation.create(:gene_id=>1,:relation_id=>7)
GenesRelation.create(:gene_id=>2,:relation_id=>8)
GenesRelation.create(:gene_id=>2,:relation_id=>9)
GenesRelation.create(:gene_id=>2,:relation_id=>10)
GenesRelation.create(:gene_id=>2,:relation_id=>11)
GenesRelation.create(:gene_id=>3,:relation_id=>12)
GenesRelation.create(:gene_id=>3,:relation_id=>13)
GenesRelation.create(:gene_id=>4,:relation_id=>12)
GenesRelation.create(:gene_id=>4,:relation_id=>13)
GenesRelation.create(:gene_id=>5,:relation_id=>14)
GenesRelation.create(:gene_id=>5,:relation_id=>15)
GenesRelation.create(:gene_id=>6,:relation_id=>17)
GenesRelation.create(:gene_id=>6,:relation_id=>14)

Report.create(:order_id=>1,:report_category_id=>1,:related_action_id=>1,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>1,:related_action_id=>2,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>1,:related_action_id=>3,:enable=>true)

Report.create(:order_id=>1,:report_category_id=>2,:related_action_id=>4,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>2,:related_action_id=>5,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>2,:related_action_id=>6,:enable=>true)

Report.create(:order_id=>1,:report_category_id=>3,:related_action_id=>7,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>3,:related_action_id=>8,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>3,:related_action_id=>9,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>3,:related_action_id=>10,:enable=>true)
Report.create(:order_id=>1,:report_category_id=>3,:related_action_id=>11,:enable=>true)

